---
- hosts: docker
  remote_user: root
  roles:
    - seitleio-default-role
    - ansible-role-docker
  tasks:
    - include_tasks: playbooks/prereqs.yml
    - include_tasks: playbooks/nginx_reverse_proxy.yml